import { useRef, useState } from 'react'
import { CaptureError, parseVoice, type CaptureResult } from './captureClient'

export function VoiceCapture({ onResult, onManual }: { onResult: (result: CaptureResult) => void; onManual: (notes?: string) => void }) {
  const [recording, setRecording] = useState(false); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null); const [transcript, setTranscript] = useState('')
  const recorder = useRef<MediaRecorder | null>(null); const stream = useRef<MediaStream | null>(null); const chunks = useRef<Blob[]>([])
  function release() { stream.current?.getTracks().forEach((track) => track.stop()); stream.current = null; recorder.current = null; chunks.current = [] }
  async function start() { setError(null); try { stream.current = await navigator.mediaDevices.getUserMedia({ audio: true }); const type = MediaRecorder.isTypeSupported('audio/webm') ? 'audio/webm' : 'audio/mp4'; const mediaRecorder = new MediaRecorder(stream.current, { mimeType: type }); recorder.current = mediaRecorder; chunks.current = []; mediaRecorder.ondataavailable = (event) => { if (event.data.size) chunks.current.push(event.data) }; mediaRecorder.onstop = async () => { let audio: Blob | null = new Blob(chunks.current, { type }); release(); setRecording(false); setLoading(true); try { const result = await parseVoice(audio); setTranscript(result.transcript ?? ''); onResult(result) } catch (caught) { if (caught instanceof CaptureError && caught.transcript) setTranscript(caught.transcript); setError(caught instanceof Error ? caught.message : 'Не удалось обработать запись.') } finally { audio = null; setLoading(false) } }; mediaRecorder.start(); setRecording(true) } catch { release(); setError('Не удалось получить доступ к микрофону.') } }
  function stop() { if (recorder.current?.state === 'recording') recorder.current.stop() }
  return <section className="section-card stack"><div><h2>Продиктуйте расход</h2><p>Назовите сумму, место, дату, категорию и кто платил.</p></div>{transcript ? <label>Распознанный текст<textarea rows={4} value={transcript} onChange={(event) => setTranscript(event.target.value)} /></label> : null}{error ? <p className="error-text" role="alert">{error}</p> : null}<div className="button-row"><button className="button secondary" type="button" onClick={() => onManual(transcript)}>Заполнить вручную</button>{recording ? <button className="button primary" type="button" onClick={stop}>Остановить запись</button> : <button className="button primary" type="button" disabled={loading} onClick={() => void start()}>{loading ? 'Разбираем…' : 'Начать запись'}</button>}</div></section>
}
